// Constants and configuration
export const ENABLE_BLE_FUNCTIONALITY = true;

export const SERVICE_PATIENTSYNC_UUID = "50DB505C-8AC4-4738-8448-3B1D9CC09CC5";
export const CHAR_CUR_ROOM_UUID = "EB6E7163-A3EA-424B-87B4-F63EB8CCB65A";
export const CHAR_CUR_PATIENT_UUID = "6DF4D135-1F8A-409E-BCA4-5265DA56DF4F";
export const CHAR_LAST_EDIT_TIME_UUID = "2727FACF-E0EC-4667-9799-BE56C80AB5B5";
export const CHAR_LAST_EDIT_USER_ID_UUID = "6A083CD6-A9D6-41A7-A9C5-B4C9C42D7FC8";

export const BLE_MGR_STATE_OFFLINE = 0x0;
export const BLE_MGR_STATE_IDLE = 0x1;
export const BLE_MGR_STATE_SEARCHING = 0x2;
export const BLE_MGR_STATE_STOPPING = 0x3;
export const BLE_MGR_STATE_CONNECTING = 0x4;
export const BLE_MGR_STATE_CONNECTED = 0x5;
export const BLE_MGR_STATE_DISCONNECTING = 0x6;
export const BLE_MGR_STATE_DISABLED = 0xfe;
export const BLE_MGR_STATE_UNKNOWN = 0xff;

export const BLE_MGR_STATES_STRS = {
    [BLE_MGR_STATE_OFFLINE]: "STATE_OFFLINE",
    [BLE_MGR_STATE_IDLE]: "STATE_IDLE",
    [BLE_MGR_STATE_SEARCHING]: "STATE_SEARCHING",
    [BLE_MGR_STATE_STOPPING]: "STATE_STOPPING",
    [BLE_MGR_STATE_CONNECTING]: "STATE_CONNECTING",
    [BLE_MGR_STATE_CONNECTED]: "STATE_CONNECTED",
    [BLE_MGR_STATE_DISCONNECTING]: "STATE_DISCONNECTING",
    [BLE_MGR_STATE_DISABLED]: "STATE_DISABLED",
    [BLE_MGR_STATE_UNKNOWN]: "STATE_UNKNOWN"
};

const BLE_MGR_ALL_STATES = [
    BLE_MGR_STATE_OFFLINE,
    BLE_MGR_STATE_IDLE,
    BLE_MGR_STATE_SEARCHING,
    BLE_MGR_STATE_STOPPING,
    BLE_MGR_STATE_CONNECTING,
    BLE_MGR_STATE_CONNECTED,
    BLE_MGR_STATE_DISCONNECTING,
    BLE_MGR_STATE_DISABLED,
    BLE_MGR_STATE_UNKNOWN
];

// TODO: Properly implement state management
export const BLE_MGR_VALID_ENTRY_STATES = {
    [BLE_MGR_STATE_OFFLINE]: BLE_MGR_ALL_STATES,
    // [BLE_MGR_STATE_IDLE]: [BLE_MGR_STATE_OFFLINE, BLE_MGR_STATE_UNKNOWN],
    [BLE_MGR_STATE_IDLE]: BLE_MGR_ALL_STATES,
    [BLE_MGR_STATE_SEARCHING]: [BLE_MGR_STATE_IDLE],
    [BLE_MGR_STATE_STOPPING]: [BLE_MGR_STATE_SEARCHING],
    [BLE_MGR_STATE_CONNECTING]: [BLE_MGR_STATE_SEARCHING, BLE_MGR_STATE_IDLE],
    [BLE_MGR_STATE_CONNECTED]: [BLE_MGR_STATE_CONNECTING],
    [BLE_MGR_STATE_DISCONNECTING]: [BLE_MGR_STATE_CONNECTED],
    [BLE_MGR_STATE_DISABLED]: BLE_MGR_ALL_STATES,
    [BLE_MGR_STATE_UNKNOWN]: BLE_MGR_ALL_STATES
};

// export const BLE_MGR_VALID_ENTRY_STATES = {
//     [BLE_MGR_STATE_OFFLINE]: BLE_MGR_ALL_STATES,
//     [BLE_MGR_STATE_IDLE]: BLE_MGR_ALL_STATES,
//     [BLE_MGR_STATE_SEARCHING]: BLE_MGR_ALL_STATES,
//     [BLE_MGR_STATE_STOPPING]: BLE_MGR_ALL_STATES,
//     [BLE_MGR_STATE_CONNECTING]: BLE_MGR_ALL_STATES,
//     [BLE_MGR_STATE_CONNECTED]: BLE_MGR_ALL_STATES,
//     [BLE_MGR_STATE_DISCONNECTING]: BLE_MGR_ALL_STATES,
//     [BLE_MGR_STATE_DISABLED]: BLE_MGR_ALL_STATES,
//     [BLE_MGR_STATE_UNKNOWN]: BLE_MGR_ALL_STATES
// };

export default {
    ENABLE_BLE_FUNCTIONALITY,
    SERVICE_PATIENTSYNC_UUID,
    CHAR_CUR_PATIENT_UUID,
    CHAR_CUR_ROOM_UUID,
    CHAR_LAST_EDIT_TIME_UUID,
    CHAR_LAST_EDIT_USER_ID_UUID,
    BLE_MGR_STATE_OFFLINE: 0x0,
    BLE_MGR_STATE_IDLE: 0x1,
    BLE_MGR_STATE_SEARCHING: 0x2,
    BLE_MGR_STATE_STOPPING: 0x3,
    BLE_MGR_STATE_CONNECTING: 0x4,
    BLE_MGR_STATE_CONNECTED: 0x5,
    BLE_MGR_STATE_DISCONNECTING: 0x6,
    BLE_MGR_STATE_DISABLED: 0xfe,
    BLE_MGR_STATE_UNKNOWN: 0xff,
    BLE_MGR_STATES_STRS,
    BLE_MGR_VALID_ENTRY_STATES
};
